services:
    postgres:
        image: postgres:14
        container_name: blank-template-db
        env_file:
            - ./env/postgres.env
        ports:
            - 5432:5432
        volumes:
            - postgres_db:/var/lib/postgresql/data
volumes:
    postgres_db:
